import random
import sympy
#prime number input
while True:
    q=int(input("Enter prime number:"))
    if((sympy.isprime(q))):
        break
    else:
        print("Please enter prime number only:")
# Generation of primitive root
primroot=q-1
b=[]
for i in range(1,q):
    a=[]
    for j in range(1,q):
        m=((i**j)%q)
        if(m in a):
            break
        else:
            a.append(m)
    if (len(a)==primroot):
        b.append(i)
print(b)
b=random.choice(b)
print("Randomly selected primitive value:(a)", b)
#Number of user input
user_list=[]
user_no=int(input("Enter number of users:"))
for i in range(0,user_no):
    print("For user:",i)
    x=int(input("Enter private key:"))
    if(x>b):
        print("Please enter private key less than primitive root value i.e:",b)
        x=int(input("Enter private key:"))
    print("\n")    
    user_list.append(x)


y=[]
k=[0 for i in range(user_no)]
for i in range(0,user_no):
    y1=(b**user_list[i])%q
    y.append(y1)
    print("Public Key of user ",i,"  = ",y[i],"\n")

for i in range(0,user_no):
    for j in range(i+1,user_no):
        print(i,"--->",j)
        k[0]=((y[j]**user_list[i])%q)
        k[1]=((y[i]**user_list[j])%q)
        print("Secret key generated by user",i,"=",k[0])
        print("Secret key generated by user",j,"=",k[1],"\n")

